// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxoeZASC4YYF7gdZcqZfoGVzq9cLuRN2M',
    appId: '1:945701944865:web:c1f153675ea5e607f22d60',
    messagingSenderId: '945701944865',
    projectId: 'fir-mandalaarenaapp',
    authDomain: 'fir-mandalaarenaapp.firebaseapp.com',
    storageBucket: 'fir-mandalaarenaapp.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDXOUEDS_CZZ_PDIEi_saJ1_qY21JdRs74',
    appId: '1:945701944865:android:67e1268192488851f22d60',
    messagingSenderId: '945701944865',
    projectId: 'fir-mandalaarenaapp',
    storageBucket: 'fir-mandalaarenaapp.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFv34ff5gWSbuJp8JjH_lnQ6D1nj60QmU',
    appId: '1:945701944865:ios:94ec7039bc42a5b0f22d60',
    messagingSenderId: '945701944865',
    projectId: 'fir-mandalaarenaapp',
    storageBucket: 'fir-mandalaarenaapp.firebasestorage.app',
    iosBundleId: 'com.example.firebaseMandalaarenaapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDFv34ff5gWSbuJp8JjH_lnQ6D1nj60QmU',
    appId: '1:945701944865:ios:94ec7039bc42a5b0f22d60',
    messagingSenderId: '945701944865',
    projectId: 'fir-mandalaarenaapp',
    storageBucket: 'fir-mandalaarenaapp.firebasestorage.app',
    iosBundleId: 'com.example.firebaseMandalaarenaapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCxoeZASC4YYF7gdZcqZfoGVzq9cLuRN2M',
    appId: '1:945701944865:web:2b8f7bc05068a38bf22d60',
    messagingSenderId: '945701944865',
    projectId: 'fir-mandalaarenaapp',
    authDomain: 'fir-mandalaarenaapp.firebaseapp.com',
    storageBucket: 'fir-mandalaarenaapp.firebasestorage.app',
  );
}
